spring.application.name=DiscoveryServer

#default port for eureka server - still need to specify
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Correct url: http://localhost:8761/