#Application properties
spring.application.name=userService
server.port = 9020
server.servlet.context-path=/api/v1/users

#DB properties
spring.datasource.url=jdbc:postgresql://localhost:5432/userDB
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

#JWT service
jwt.secretKey = 123gfhastdrdrdrdrdrdrdgsgsararara234